// <auto-generated />
using System;
using ARAPlus.Stichprobeneditor.Repository.Impl.MSSQLServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ARAPlus.Stichprobeneditor.ConsoleAppTest.Migrations
{
    [DbContext(typeof(StichprobenContext))]
    [Migration("20210302150442_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ARAPlus.Stichprobeneditor.Models.Artikel", b =>
                {
                    b.Property<int>("ArtikelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Absatzmenge")
                        .HasColumnType("float");

                    b.Property<string>("ArtikelNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtikelId");

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("ARAPlus.Stichprobeneditor.Models.Packstoff", b =>
                {
                    b.Property<int>("PackstoffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.Property<string>("PackstoffCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PackstoffId");

                    b.HasIndex("ArtikelId");

                    b.ToTable("Packstoffs");
                });

            modelBuilder.Entity("ARAPlus.Stichprobeneditor.Models.Packstoff", b =>
                {
                    b.HasOne("ARAPlus.Stichprobeneditor.Models.Artikel", "Artikel")
                        .WithMany("Packstoffe")
                        .HasForeignKey("ArtikelId");

                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("ARAPlus.Stichprobeneditor.Models.Artikel", b =>
                {
                    b.Navigation("Packstoffe");
                });
#pragma warning restore 612, 618
        }
    }
}
